c_program_build:
	gcc -fPIC -shared -o timedAcq_new.so timedAcq.c -lncurses -lwiringPi -Wall -lrt
init_build:
	gcc -fPIC -shared -o tacqn.so tacqn.c -lncurses -lwiringPi -Wall -lrt
UI_program_Run:
	sudo python3 main.py

    
